### ISSUE TITLE
pmb.center_molecule_in_simulation_box fails for non-cubic boxes

### ISSUE THREAD

**Issue by kosovan** [pyMBE-dev/pyMBE#43]
Current implementation

box_center = [espresso_system.box_l[0]/2.0]*3

should be replace with

box_center = [
                espresso_system.box_l[0]/2.0,
                espresso_system.box_l[1]/2.0, 
                espresso_system.box_l[2]/2.0
                ]

**Comment by pm-blanco** [comment]
@paobtorres could you please take care of this?
