### ISSUE TITLE
SEED should be a global variable

### ISSUE THREAD

**Issue by pm-blanco** [pyMBE-dev/pyMBE#44]
The seed for the RNG should be a mandatory argument of  `__init__`   so that one provides it when creating an instance of pyMBE:
```python
pmb = pyMBE_library(SEED=42)
```

and it is internally stored as an attribute of `pmb`

```python
__init__(self, SEED, temperature=None, unit_length=None, unit_charge=None):
        self.SEED=SEED
```

then all methods of pyMBE should access to this value instead of having multiple SEEDs values. This implementation would make debugging of scripts using pyMBE much easier and would also also make our CI tests more consistent.

Thank you @kosovan for reporting this issue.

**Comment by pm-blanco** [comment]
@davidbbeyer maybe you can take a look at this?

**Comment by davidbbeyer** [comment]
@pm-blanco Yes, I was actually planning to make this my next contribution :)
