### ISSUE TITLE
Add an explanation how to cite pyMBE

### ISSUE THREAD

**Issue by davidbbeyer** [pyMBE-dev/pyMBE#49]
We currently do not mention our preprint anywhere in the repository except in `samples/Beyer2024/README.md`, which is a bit hidden. I think it would be a good idea to add a short note on how to cite the project, e.g. in the main README, similar to how it is done for ESPResSo.

**Comment by pm-blanco** [comment]
I agree, we should add a note in the README. Eventually, we should add a cite funtionality as mentioned in #5, which could provide the user with a list of references that should cite depending on the resources that it has activated in pyMBE, including a citation to our library.
