### ISSUE TITLE
Add copyright notice to source files.

### ISSUE THREAD

**Issue by davidbbeyer** [pyMBE-dev/pyMBE#53]
@pm-blanco Like it is done for instance also in ESPResSo, we should add a notice regarding the copyright and exclusion of warranty to _every_ source file. The following is suggested by the Free Software Foundation:

> \<one line to give the program's name and a brief idea of what it does.\>
> Copyright (C) \<year\>  \<name of author\>
> 
> This program is free software: you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation, either version 3 of the License, or
> (at your option) any later version.
> 
> This program is distributed in the hope that it will be useful,
> but WITHOUT ANY WARRANTY; without even the implied warranty of
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> GNU General Public License for more details.
> 
> You should have received a copy of the GNU General Public License
> along with this program.  If not, see <http://www.gnu.org/licenses/>.

A corresponding note should also be displayed on the CLI if pyMBE is used:

> \<program\>  Copyright (C) \<year\>  \<name of author\>
> This program comes with ABSOLUTELY NO WARRANTY; for details type \`show w'.
> This is free software, and you are welcome to redistribute it
> under certain conditions; type \`show c' for details.

**Comment by jngrad** [comment]
Please note I have just opened a massive PR that will interfere with this work: #55. I modified import statements in a dozen files, which might cause merge conflicts with license headers.

**Comment by jngrad** [comment]
Now would be the right time to update all files with a license header.
