### ISSUE TITLE
Introduce a Changelog

### ISSUE THREAD

**Issue by pm-blanco** [pyMBE-dev/pyMBE#66]
In other to help admins and users of library, we should start maintaining a changelog starting with the upcoming first stable version of pyMBE. The suggested format is to use [Keep A Changelog 1.1.0](https://keepachangelog.com/en/1.1.0/).

**Comment by jngrad** [comment]
Do we still have deprecated or unused functions lying around? Once we have a changelog in place, every time we remove a deprecated function, we must add an extra line in the changelog to document it as an API change.

**Comment by pm-blanco** [comment]
@jngrad I believe that I managed to remove all of them from `pymbe.py` but I still need to do a proper clean-up of the library modules. I will do it before the release of 0.8 to try to minimize the number of API changes as much as possible

**Comment by jngrad** [comment]
For completeness, [Common Changelog](https://common-changelog.org/) is quite similar and better documented, but isn't widely adopted yet.
